name: counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  auto_reload:
    path: ..

  flutter:
    sdk: flutter

  http: 0.12.0+2

flutter:
  uses-material-design: true
